import { robotoFont } from './config/fonts'
import './globals.css'

export const metadata = {
  title: 'well shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoFont.className}>{children}</body>
    </html>
  )
}
